# Generated by Django 4.0.5 on 2022-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_title_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 chars', max_length=20, verbose_name='ISBN'),
        ),
    ]
