# Generated by Django 4.0.5 on 2022-06-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_unit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='unit_file',
            field=models.FileField(blank=True, help_text='Загрузите электронный вариант', null=True, upload_to='books', verbose_name='Электронный экземпляр'),
        ),
    ]
