# Generated by Django 4.0.5 on 2022-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, help_text='Загрузите обложку', null=True, upload_to='books/image', verbose_name='Обложка книги'),
        ),
    ]
